# config.yaml
source_path: "./lakebridge/input"
target_path: "./lakebridge/output"
dialect: "Synapse"
profile: "lakebridge"
debug: false
run_validation: true
run_analyzer: true
run_transpiler: true
